# Generated by Django 6.0.3 on 2026-03-18 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_loginhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.CharField(help_text='Image filename or path', max_length=255)),
                ('category', models.CharField(choices=[('featured', 'Featured'), ('new_arrival', 'New Arrival'), ('regular', 'Regular')], default='regular', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
