# Generated by Django 5.1.3 on 2026-03-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_contact_id_alter_customuser_id_and_more"),
        ("store", "0006_userlocation"),
    ]

    operations = []
