# Generated by Django 5.1.3 on 2026-03-31 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_wishlist"),
        ("store", "0007_merge_20260321_1519"),
    ]

    operations = []
