# Generated by Django 5.2.15 on 2026-06-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_merge_0006_wishlist_0007_merge_20260321_1519"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlocation",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
