# Generated by Django 6.0.6 on 2026-06-19 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_customuser_phone_order_product_description_and_more"),
        ("store", "0010_alter_contact_id_alter_customuser_id_and_more"),
    ]

    operations = []
