# Generated by Django 6.0.3 on 2026-07-11 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_payment_method_order_payment_status_and_more'),
        ('store', '0011_merge_20260619_0815'),
    ]

    operations = [
    ]
