# Generated by Django 6.0.3 on 2026-07-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_add_order_address_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.CharField(help_text='Image filename or path', max_length=500)),
                ('link', models.CharField(blank=True, default='/shop', max_length=255)),
                ('position', models.CharField(choices=[('main', 'Main Banner (Center)'), ('small', 'Small Banner (Half Width)'), ('bottom', 'Bottom Banner (Third Width)')], default='main', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
