# Generated by Django 6.0.3 on 2026-07-11 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_promobanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percentage', models.PositiveIntegerField(help_text='Discount in percentage (0-100)')),
                ('max_uses', models.PositiveIntegerField(default=100)),
                ('current_uses', models.PositiveIntegerField(default=0)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('show_on_popup', models.BooleanField(default=False)),
                ('popup_text', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_in', to='store.product'),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='image',
            field=models.CharField(blank=True, default='', help_text='Image filename or path', max_length=500),
        ),
        migrations.AlterField(
            model_name='promobanner',
            name='position',
            field=models.CharField(choices=[('main', 'Main Banner (Center)'), ('small', 'Small Banner (Half Width)'), ('bottom', 'Bottom Banner (Third Width)'), ('promo', 'Promo Code Bar (Top Announcement)')], default='main', max_length=20),
        ),
    ]
