# Generated by Django 6.0.3 on 2026-07-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_category_product_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Setting key, e.g., 'estimated_delivery_time'", max_length=100, unique=True)),
                ('value', models.TextField(help_text="Setting value, e.g., '4-5 business days'")),
                ('description', models.CharField(blank=True, help_text='Optional description of the setting', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
