# Generated by Django 6.0.3 on 2026-07-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_companysetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='group_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
