# Generated by Django 6.0.3 on 2026-07-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_productfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcolor',
            name='image',
            field=models.CharField(blank=True, help_text='Image filename or path', max_length=255, null=True),
        ),
    ]
