# Generated by Django 6.0.3 on 2026-07-13 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_productcolor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=255)),
                ('product_color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_images', to='store.productcolor')),
            ],
        ),
    ]
