# Generated by Django 6.0.3 on 2026-07-13 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_productsize_discount_price_productsize_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='store.productcolor'),
        ),
    ]
