# Generated by Django 6.0.3 on 2026-07-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_productsize_color'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productrating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productrating',
            name='color',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='productrating',
            unique_together={('user', 'product_name', 'color')},
        ),
    ]
