# Generated by Django 6.0.3 on 2026-07-14 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_order_delivery_fee_order_gst_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promobanner',
            name='product_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_in', to='store.productsize'),
        ),
    ]
